### ISSUE TITLE
Alexa sees Shelly Plug S as a Temperature sensor

### ISSUE THREAD

**Issue by ktriponis** [ShellyUSA/Hubitat-Drivers#10]
After syncing hubitat devices with Alexa, Shelly Plug S appears as a "Temperature sensor" rather than a "Plug" or at least a "Switch". Since it's marked as a sensor, there is no way to actually control it, the only thing that I get when I click on the "sensor" in Alexa is a big number 0.0 which makes it not usable even as a sensor due to an incorrect reading.

**Comment by ktriponis** [comment]
P.S., If this is a non-trivial thing to achieve, it's still possible to use a **Virtual Switch** to get the job done, which might be even a better option not exposing the actual device to Alexa, but still think it should be possible to do if desired.

**Comment by sgrayban** [comment]
Nothing I can do about this. It's a change in how Hubitat coded the new
Alexa Skill which I have pointed out to the code monkeys but they don't
seem to care.
