### ISSUE TITLE
Missing support/drivers for Shelly Uni and i3

### ISSUE THREAD

**Issue by HVR88** [ShellyUSA/Hubitat-Drivers#11]
Would love to have both of these supported via MQTT

There are at least two Uni drivers from Hubitat users linked in their forums, but honestly, they're beyond useless.

**Comment by sgrayban** [comment]
What is wrong with them ?

**Comment by HVR88** [comment]
Have you looked at them?  Cobra's needs to use polling. That's a complete non-starter for any sensor-based device. Tomw's requires installing 4 nonsensical driver files. It's all a complete mess done by someone who doesn't know what they're doing.

**Comment by sgrayban** [comment]
No I haven't because I have no reason to need them at my house, this is something I have said over and over. I'll have to ask Doug if he will help me create a test setup here that doesn't cost any money to build. I don't get paid for this code work and I no longer have a job.

**Comment by jeremyakers** [comment]
I'm a little confused here. I thought Allterco Robotics took over ownership of this repo? Why wouldn't they be able to take on the work of writing this driver for their own devices?

**Comment by sgrayban** [comment]
Because I am the only one who uses hubitat and coded the drivers. Allterco uses HA as far as I know and I coded the drivers years before Allterco even listed hubitat as a supported hub.
