### ISSUE TITLE
Shelly RGBW2 White

### ISSUE THREAD

**Issue by neilcavendish** [ShellyUSA/Hubitat-Drivers#26]
Hey,

This is not an issue exactly but I am not sure where else to ask this question. 

I installed the drivers and it has connected to my shelly no problem. Within the device page I see the 4 channels and there levels. This all works and the light turns on and off no problem. 

What I want to know is how do I add this to the dashboard, one on/off and dimmer per channel. 

thanks

**Comment by sgrayban** [comment]
Add the device to the dashboard.... you can ask for more help on on the Hubitat forum.

**Comment by sgrayban** [comment]
unrelated to driver code
