### ISSUE TITLE
Shelly Duo color temperature not working

### ISSUE THREAD

**Issue by dmitripr** [ShellyUSA/Hubitat-Drivers#4]
Added Shelly Duo to my Hubitat Elevation 2.2.3.148. 

Changing color temperature works from the direct interface on the bulb, but from Hubitat does not work 100%. It's only possible to set either 2700 or 6500, no values in between. Setting values < 6500 sets to 2700 only. If I enter 6500 and above, then it sets to 6500.

**Comment by sgrayban** [comment]
I just checked this and it works for me. How are you trying to set it? The dashboard or device page?

**Comment by dmitripr** [comment]
It’s working fine after I upgraded the firmware to the latest version. When I first installed the bulbs it didn’t tell me that a new firmware was available. 

Closing the issue.
